### ISSUE TITLE
Issue on the Paper version 345

### ISSUE THREAD

**Issue by bobhenl** [MyzelYam/DiscoFloor#1]
Hi, I'm getting this error on the newest paper version, could you fix it please?
```
[16:59:43 WARN]: [DiscoFloor] Plugin DiscoFloor v1.4.0 generated an exception while executing task 7263
java.lang.IllegalStateException: Asynchronous ChunkMapDistance::addTicket!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.15.2.jar:git-Paper-345]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:158) ~[patched_1.15.2.jar:git-Paper-345]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.addTicket(ChunkMapDistance.java:311) ~[patched_1.15.2.jar:git-Paper-345]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.addTicket(ChunkProviderServer.java:958) ~[patched_1.15.2.jar:git-Paper-345]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:402) ~[patched_1.15.2.jar:git-Paper-345]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.getChunkAt(CraftWorld.java:410) ~[patched_1.15.2.jar:git-Paper-345]
at org.bukkit.craftbukkit.v1_15_R1.block.CraftBlock.getChunk(CraftBlock.java:128) ~[patched_1.15.2.jar:git-Paper-345]
at de.myzelyam.discofloor.BlockChangePacketMgr$1.run(BlockChangePacketMgr.java:64) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-345]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-345]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-345]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by JanTuck** [comment]
It is simply his code that sucks, he should not get anything related to the world async.. which he does.

**Comment by bobhenl** [comment]
And could someone try to fix it? I didn't find alternative on Spigot :/

**Comment by LeonMangler** [comment]
It looks like I forgot to move that code when I made it async, so yes that will definitely be fixed. Unfortunately there are more issues than that for making it work on latest spigot. With the material changes the WrappedBlockData constructor in protocollib doesnt work in the same way as it used to anymore. I've pushed a commit with some updates (which also improves upon the async error) but there is more work needed for which I currently dont have enough time. I'd appreciate PRs though.

**Comment by bobhenl** [comment]
And could I download somewhere atleast fixed async?

**Comment by bobhenl** [comment]
Tried decompile myself and got this:
```
[14:27:26 WARN]: [DiscoFloor] Plugin DiscoFloor v1.4.1 generated an exception while executing task 3316
java.lang.IllegalArgumentException: bound must be positive
at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:310) ~[?:?]
at de.myzelyam.discofloor.DiscoFloorPlugin.getRandomFloorBlockData(DiscoFloorPlugin.java:58) ~[?:?]
at de.myzelyam.discofloor.BlockChangePacketMgr$1.run(BlockChangePacketMgr.java:84) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-367]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-367]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-367]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
[14:27:27 WARN]: [DiscoFloor] Plugin DiscoFloor v1.4.1 generated an exception while executing task 3348
java.lang.IllegalArgumentException: bound must be positive
at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:310) ~[?:?]
at de.myzelyam.discofloor.DiscoFloorPlugin.getRandomFloorBlockData(DiscoFloorPlugin.java:58) ~[?:?]
at de.myzelyam.discofloor.BlockChangePacketMgr$1.run(BlockChangePacketMgr.java:84) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-367]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-367]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-367]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by bobhenl** [comment]
@MyzelYam how it looks please?

**Comment by LeonMangler** [comment]
That error occurs when there isn't a single configured floor block. This is likely because you havent updated your config file in a while and it's still using the old numeric IDs which are broken now. If you regenerate it or enter materials it should work.
Edit: Seems like Spigot's sendBlockChange method is now broken too... I'll commit my changes but it's still broken

**Comment by bobhenl** [comment]
Could you release new version @MyzelYam with these fixes? Maybe also with support for 1.16.1?

**Comment by bobhenl** [comment]
Can't give myself wand...
```
org.bukkit.command.CommandException: Unhandled exception executing command 'discofloor' in plugin DiscoFloor v1.4.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-375]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-375]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1866) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1674) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1232) ~[patched_1.15.2.jar:git-Paper-375]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-375]
at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NoSuchFieldError: GOLD_AXE
at de.myzelyam.discofloor.DiscoFloorCommandExecutor.onCommand(DiscoFloorCommandExecutor.java:135) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-375]
... 17 more
```

+ when using old data I'm getting this: https://pastebin.com/7imQNsiS

Btw I tried delete old data, but I can't create it with wand, when I'm getting error when using /disclofloor wand command 

@MyzelYam

**Comment by bobhenl** [comment]
How it looks @MyzelYam ?

**Comment by bobhenl** [comment]
@MyzelYam ?

**Comment by bobhenl** [comment]
Please @MyzelYam

**Comment by LeonMangler** [comment]
Finally found the time to update it, this should be solved now.

**Comment by bobhenl** [comment]
Yeah, works. Closing issue. Thanks for fixing.
