### ISSUE TITLE
Error again

### ISSUE THREAD

**Issue by bobhenl** [MyzelYam/DiscoFloor#2]
Hi, i'm using 1.16.3 and getting this error now, could you fix please?
```
[03:15:30] [Craft Scheduler Thread - 24/WARN]: [DiscoFloor] Plugin DiscoFloor v1.4.2 generated an exception while executing task 5397
com.comphenix.protocol.reflect.FieldAccessException: No field with type net.minecraft.server.v1_16_R2.ChunkCoordIntPair exists in class PacketPlayOutMultiBlockChange.
	at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:363) ~[?:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:343) ~[?:?]
	at de.myzelyam.discofloor.BlockChangePacketMgr$1.run(BlockChangePacketMgr.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-246]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-246]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-246]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

 @MyzelYam

**Comment by LeonMangler** [comment]
Mojang decided to change the chunk packets in 1.16.2/3 again, so only 1.16 works with ProtocolLib... You can turn off ProtocolLib packets in the config since the API alternative still works. Not sure when I'll have time to redo the chunk packets again.
